### ISSUE TITLE
Twitter API

### ISSUE THREAD

**Issue by ld-web** [PikkMoune71/projet-react-ynov#13]
Hello !

Bon je me suis penché sur le sujet de l'API Twitter, en réalité l'échec sur la requête preflight est simplement dû au fait qu'on ne peut pas utiliser l'API depuis un navigateur, voilà tout.
C'est pour ça que ça fonctionnait très bien dans l'application de l'étudiant qui avait fait un backend NestJS l'année dernière, parce que c'était côté serveur...je m'étais pas attardé sur ce point mais je pense vraiment que c'est ça. Aussi, dans [cette réponse sur StackOverflow](https://stackoverflow.com/a/35898961), on n'est visiblement pas les seuls à avoir le problème...

Du coup je vous ai monté vite fait un petit backend Node + Express : https://github.com/ld-web/twitter-api-express-client

Normalement vous avez tout dans le README, l'idée vous l'aurez deviné, c'est de pouvoir lancer votre petit backend à côté de votre application React, puis d'appeler ce backend depuis votre application ReactJS.
Certes, ça va changer un peu la codebase du côté React...mais vous pouvez garder l'idée des `computeUrl` dans la mesure où ça change le endpoint à appeler selon qu'on appelle Twitter, LinkedIn, etc...on pourra en reparler la semaine prochaine.

Dans tous les cas, normalement vous pouvez clôner, vous déclarez vos variables d'environnement dans un `.env`, vous faites un petit `npm i` puis `node index.js` et ça devrait fonctionner !

> Une petite note, si avec Chrome vous avez  des erreurs CORS => utilisez Firefox, chez moi c'est passé !

Voilà, désolé pour le délai de traitement de votre souci, j'espère que tout ça vous ira ! Commentez ci-dessous bien sûr si besoin 👍🏻

**Comment by TheoRamousse** [comment]
Merci, le back fonctionne parfaitement. J'ai quand même dû modifier la liste des paramètres de l'URL twitter en local car nous en avons ajouté de nouveaux :)

**Comment by ld-web** [comment]
Parfait ! On fera un point là-dessus mercredi, j'ai prévu une petite partie sur le routing et l'API Context, puis de repasser vers chacun des groupes pour discuter des avancées et préparer les présentations orales 😊
Je ferme donc ce thread.
